"""
compare_scatter_labels.py

Compare scatter results from different labels (different runs/parameters).
Reads pickle files generated by fit_custom_scatter.py and plots them
in a style similar to fig8 in jianbing.
"""

# %%
import sys
import pickle
from pathlib import Path


# ---------- project root setup ----------
current_dir = Path.cwd().resolve()
marker = "pyproject.toml"
root_path = None

while True:
    if not current_dir or current_dir == current_dir.parent:
        break
    if (current_dir / marker).exists():
        root_path = current_dir
        break
    else:
        current_dir = current_dir.parent

if root_path:
    root_path_str = str(root_path)
    if root_path_str not in sys.path:
        sys.path.append(root_path_str)
    from initial import *
else:
    print("Error: Could not find project root.")
    sys.exit(1)

# %% ---------- runtime settings ----------
# Add your labels here
LABELS = ["s16a_logm_50_100", "s16a_redm_hsc", "pdr3_redm_hsc", "huang2022_logm_50_100", "huang2022_redm_hsc"]
# Optional: display names for labels in the legend
DISPLAY_NAMES = {}

# Colors and markers for different labels
COLORS = ["#33a02c", "#984ea3", "#ff7f00", "#1f78b4", "#e41a1c"]
MARKERS = ["H", "P", "s", "o", "D"]

# Hardcoded rho bins as they might be missing from some pkl files
# Units: Mpc^-3
RHO_BINS = np.array(
    [
        5.315651368706627e-07,
        2.0035916697432675e-06,
        6.7467882756661044e-06,
        1.184776910832881e-05,
    ]
)

OUTPUT_DIR = root_path / "output/comparison/plots"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

# %% ---------- load data ----------
data_dict = {}

for label in LABELS:
    pkl_path = root_path / f"output/{label}/pkl/custom_samples_sum.pkl"
    if not pkl_path.exists():
        print(f"Warning: {pkl_path} does not exist. Skipping.")
        continue

    with open(pkl_path, "rb") as f:
        res = pickle.load(f)
        # fit_custom_scatter.py saves it under the key "custom_sample"
        data_dict[label] = res["custom_sample"]

print(f"Loaded data for: {list(data_dict.keys())}")

# %% ---------- plotting ----------
plt.rcParams["mathtext.fontset"] = "stix"
plt.rcParams["font.size"] = 14

fig = plt.figure(figsize=(10, 7))
ax1 = fig.add_subplot(111)

# Style setup similar to fig8
ax1.set_xscale("log", nonpositive="clip")
ax1.grid(False)

for i, label in enumerate(data_dict.keys()):
    sum_tab = data_dict[label]

    # Use hardcoded rho bins
    x_val = RHO_BINS
    y_val = sum_tab["sig_med_bt"]
    y_err = sum_tab["sig_err_bt"]

    # Use the original index in LABELS to keep style consistent
    idx = LABELS.index(label)
    color = COLORS[idx % len(COLORS)]
    marker = MARKERS[idx % len(MARKERS)]
    display_name = DISPLAY_NAMES.get(label, label)

    # Shaded region for error
    ax1.fill_between(x_val, y_val - y_err, y_val + y_err, color=color, alpha=0.2)

    # Scatter points with horizontal offset
    offset = 1.0 + 0.05 * (i - (len(data_dict) - 1) / 2.0)
    ax1.scatter(
        x_val * offset,
        y_val,
        s=150,
        marker=marker,
        alpha=0.9,
        facecolor=color,
        edgecolor="k",
        linewidth=1.5,
        label=display_name,
    )

# Labeling
ax1.set_xlabel(r"$N (>M)\ [\rm Mpc^{-3}]$", fontsize=20)
ax1.set_ylabel(r"$\sigma_{\mathcal{M}|\mathcal{O}}\ [\rm dex]$", fontsize=20)
ax1.legend(loc="best", fontsize=15)

# Invert x-axis: density decreases from left to right
# This puts the most common/least massive bins on the left
ax1.set_xlim(np.max(RHO_BINS) * 1.5, np.min(RHO_BINS) * 0.5)

# Add bin labels
for i, rho in enumerate(RHO_BINS):
    ax1.text(
        rho,
        ax1.get_ylim()[1] * 0.95,
        f"Bin {i + 1}",
        horizontalalignment="center",
        fontsize=12,
    )

plt.tight_layout()
plt.show()
